name: WitherCustomShield           
version: 0.0.7
main: welfare93.wcs.WitherCustomShield
commands:
  radiation:
    aliases: [rad]
    description: executes the "shorthand" commands
    usage: /<command>