name: ${project.name}
version: ${project.version}
description: ${project.description}
author: welfare93
website: https://github.com/Majncraft/WitherCustomShield
main: welfare93.wcs.WitherCustomShield
